name: publish to npm
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 24.x
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run test
    - run: npm run build
    - run: npm publish  --access public
      
      
